"""Initial migration

Revision ID: 1c90f047c8ce
Revises: None
Create Date: 2015-08-23 23:37:16.777701

"""

# revision identifiers, used by Alembic.
revision = '1c90f047c8ce'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.INTEGER()),
    sa.Column('name', sa.VARCHAR()),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER()),
    sa.Column('name', sa.VARCHAR()),
    sa.Column('password', sa.VARCHAR()),
    sa.Column('role_id', sa.INTEGER()),
    sa.ForeignKeyConstraint(['role_id'], [u'roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():


    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('roles')
    ### end Alembic commands ###
