"""empty message

Revision ID: 40d8293f88f
Revises: 9d5b76509d5
Create Date: 2015-09-09 22:37:33.422016

"""

# revision identifiers, used by Alembic.
revision = '40d8293f88f'
down_revision = '9d5b76509d5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('locale', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locale')
    ### end Alembic commands ###
