"""empty message

Revision ID: 59710699ea57
Revises: 1c90f047c8ce
Create Date: 2015-08-26 23:11:35.754471

"""

# revision identifiers, used by Alembic.
revision = '59710699ea57'
down_revision = '1c90f047c8ce'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String()))
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR())
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR())
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR())
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR())
    op.drop_column('users', 'email')
    ### end Alembic commands ###
